### ISSUE TITLE
setCompletions方法 perfix 无法获得.符号

### ISSUE THREAD

**Issue by cookieY** [wangjianhui2464/vue2-ace-editor-support-chinese#2]
setCompletions 的prefix 无法识别.这个符号

**Comment by dahui4dev** [comment]
@cookieY  你们是怎么使用的呢？

**Comment by cookieY** [comment]
@wangjianhui2464 你好  我们是打算用来做mysql的自动补全 在Mysql补全当中 我需要用.的符号去获得对应库的对应表名
